name = "JMC MTR Lets Play Server"
author = "JMC Team"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a457d3613799d1dd63149eae5c8b0efbc6da85d9376e7b57d91deab50c12bb52"

[versions]
fabric = "0.16.10"
minecraft = "1.19.4"
