name = "JMC MTR Lets Play Server"
author = "JMC Team"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d92778bfc9f050fdb3629ca66289a31bb6634c567d547b6e4e5ff828fe647ff"

[versions]
fabric = "0.16.10"
minecraft = "1.19.4"
