name = "JMC MTR Lets Play Server"
author = "JMC Team"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3d3f524126cb709376c4fa2624b02a13523e63c96ff7ab6a9a55f14f370880c"

[versions]
fabric = "0.16.10"
minecraft = "1.19.4"
